### ISSUE TITLE
[BUG] Drag Ruler Persisting

### ISSUE THREAD

**Issue by AnnaMayBelle** [caewok/fvtt-elevation-ruler#124] opened 2024-07-03 18:50 UTC
I just started using Elevation Ruler and while I love its functionality, I'm a bit bothered by the fact that the lines displaying where another player has moved remain on screen. I run very roleplay heavy games where tokens tend to move a lot outside of combat, and leaving colored squares and lines everywhere is a sad distraction. Could this be made a toggle, so I could use the feature during combat only?

![image](https://github.com/caewok/fvtt-elevation-ruler/assets/32752060/ec672ca2-1548-4d30-b8ca-874993f1cda5)

**Comment by caewok** [comment] 2024-07-04 00:17
It is not supposed to be leaving colored squares and lines everywhere. Do you mean displaying the colored squares and lines when using the ruler, or do you mean it is keeping the colored squares and lines even after the player's token has completed a movement? 

Presuming the latter, it sounds like a bug. What version of Foundry, what system, and what version of Elevation Ruler are you using?

**Comment by Geektasticdad** [comment] 2024-07-04 13:47
I have this same problem. Running Foundry 12.328, DnD5e 3.2.1, and Elevation Ruler 0.9.8. After the player character moves, the trail remains.

![image](https://github.com/caewok/fvtt-elevation-ruler/assets/73676044/2cb26b01-be77-4746-ba47-7fb9d160e2e3)

**Comment by AnnaMayBelle** [comment] 2024-07-04 14:32
Oop! Well, glad it's a bug, and glad it's not just me.

Foundry v12, Build 328
Pathfinder 2nd Edition, 6.0.4
Elevation Ruler 0.9.8

**Comment by AnnaMayBelle** [comment] 2024-07-04 18:27
For the sake of troubleshooting, here's all the modules I'm using as well.

Automated Animations 4.2.74
Carousel Combat Tracker 3.0.3
Dice So Nice! 4.6.10
Elevation Ruler 0.9.8
Find The Culprit 2.1.2
Forgotten Adventures Battlemaps 1.0.62
FXMaster 4.0.2 [!]
JB2A - Jules and Ben's Animated Assets - Free Content 0.6.9
libWrapper 1.12.13.1
Monk's Active Tile Triggers 12.01
Monk's Bloodsplats 12.01
Monk's Combat Details  12.01
Monk's Combat Marker 12.01
Monk's Enhanced Journal 12.01
Monk's Little Details 12.02
Monk's Scene Navigation 12.01
Monk's TokenBar 12.01
Monk's Wall Enhancement 12.01
Moulinette Core 12.0.0
Moulinette Game Icons (module) 12.0.0
Moulinette Tiles (module) 12.1.3
Narrator Tools 0.79 [!]
PF2e Animation Macros 2.18.1
PF2e Companion Compendia 6.3 [!]
PF2e Dailies 3.5.2
PF2e Dorako UI 3.5.7
PF2e Dorako UX 1.4.2
PF2e Mercenary Marketplace Volume 1 4.0.0
PF2e Modifiers Matter 1.10.1
PF2e Ranged Combat 6.3.4
PF2e Toolbelt 2.7.8
PF2e Workbench 6.6.5
PopOut! 2.18
Sequencer 3.2.9
socketlib 1.0.13 [!]
Tagger 1.5.0
The Forge 1.14.9
Tile Sort 2.0
Tokenizer 4.3.10
Universal Battlemap Importer 4.0.0

@Geektasticdad, how much overlap do you have with my mod list? Maybe if it's a conflict we can track it down.
(BTW, any mods marked with [!] are ones not certified to with with Foundry 12, but I hadn't had issues with them on their own)

**Comment by Vengrath97** [comment] 2024-07-04 20:58
Maybe it will be of some help, but i have the same bug. 
![image](https://github.com/caewok/fvtt-elevation-ruler/assets/95933584/192250e8-87a8-4fb5-98bd-546e67e6ed45)
I get (repeating a lot) this error in the console.

As for the overlap of modules, i have: 

Automated Animations 4.2.74
Carousel Combat Tracker 3.0.3
Dice So Nice! 4.6.10
Elevation Ruler 0.9.8
FXMaster 4.0.2 [!]
libWrapper 1.12.13.1
Monk's Active Tile Triggers 12.01
Monk's Bloodsplats 12.01
Monk's Combat Details 12.01
Monk's Combat Marker 12.01
Monk's Enhanced Journal 12.01
Monk's Little Details 12.02
Monk's Scene Navigation 12.01
Monk's TokenBar 12.01
Monk's Wall Enhancement 12.01
Sequencer 3.2.9
socketlib 1.0.13 [!]

In common (and then some), but the problem persists even with Monk's modules disabled.

**Comment by jdwpom** [comment] 2024-07-07 04:37
I get ghost trails of players' -last- movements. If I move a token after my player has moved it (leaving a trail), the trail remains where it was, rather than forming a new one. This happens with only Elevation Ruler and various libraries enabled (via FindTheCulprit). Please see attached video - left side is connected player, right side is GM's screen. Can also confirm the same happens if the GM moves the token for the player, so yeah. If someone other than you moves a token, you get to see the trail from the movement. 

https://github.com/caewok/fvtt-elevation-ruler/assets/892293/a50eddd6-4bef-4f19-802e-b6919969d4a3

Edit: for completeness, here's the list of mods running in the above video. 
![image](https://github.com/caewok/fvtt-elevation-ruler/assets/892293/e2f76f8d-b9d7-44bc-b509-f89811e5ef64)

Edit: There is no error message in the console on either the player's client or the GMs client in the above video. I couldn't figure out how to capture both full monitors.

**Comment by AnnaMayBelle** [comment] 2024-07-07 05:13
Okay, so if it's happening for you with only Elevation Ruler and scant libraries, let's start looking at other commonalities!

My player and I are both using Windows 10 (64 bit), both using Chrome v126.0.6478.127. He's playing in Incognito Mode with no extensions as well (to address a weird issue he was having with Dice So Nice), but has also tested in his regular browser and still has the same problem. We're also playing via Forge.vtt. No error messages in the console for us either.

**Comment by jdwpom** [comment] 2024-07-07 05:39
Win11 64-bit, Chrome 126.0.6478.127, which is latest version. Self-hosted Node.js Foundry 12.328 .

Major edit: If I, as GM, move a token (turns out NPC rulers are also displayed on my player's screens, even with 'Hide GM Token Ruler' enabled, the trail remains. If I refresh my browser, the trail on their screen disappears. This works both ways, so player trail on GM screen disappears when player browser refreshes, too. 

The trails persist through scene changes - open a scene, let player drag a token, change scene, then go back to the active scene, and the trail remains. This is not to be confused with activating a scene, which clears the trail.

**Comment by AnnaMayBelle** [comment] 2024-07-07 17:26
> If I refresh my browser, the trail on their screen disappears. This works both ways, so player trail on GM screen disappears when player browser refreshes, too.

Holy smokes, that's a heck of a find! I wonder if, somehow, the issue is that the "a token is being moved" signal never ends. It shows the route while the token is in motion, but never clears it because it doesn't really communicate that the token is not moving anymore.

**Comment by Geektasticdad** [comment] 2024-07-08 01:12
> I get ghost trails of players' -last- movements. If I move a token after my player has moved it (leaving a trail), the trail remains where it was, rather than forming a new one. This happens with only Elevation Ruler and various libraries enabled (via FindTheCulprit). Please see attached video - left side is connected player, right side is GM's screen. Can also confirm the same happens if the GM moves the token for the player, so yeah. If someone other than you moves a token, you get to see the trail from the movement.
> 
>  Elevation.Ruler.Demo.mp4 
> Edit: for completeness, here's the list of mods running in the above video. ![image](https://private-user-images.githubusercontent.com/892293/346311575-e2f76f8d-b9d7-44bc-b509-f89811e5ef64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MDE0MDYsIm5iZiI6MTcyMDQwMTEwNiwicGF0aCI6Ii84OTIyOTMvMzQ2MzExNTc1LWUyZjc2ZjhkLWI5ZDctNDRiYy1iNTA5LWY4OTgxMWU1ZWY2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQwMTExNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MjQzOTc5ZTM5MzRiNGExNDEzZGFhMjUwM2UwNmM2NWYxNTNmNmIyZDZmMzAxMmFlMzVjNjc5NzQ4YzY2NGM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Jg-VoW-RzLwk2OoWteGdGWCvFR_3STLhBhQm9L6ca8w)
> 
> Edit: There is no error message in the console on either the player's client or the GMs client in the above video. I couldn't figure out how to capture both full monitors.

Can confirm, this happens for me too. Interesting!

**Comment by jdwpom** [comment] 2024-07-08 07:22
Managed to get one of my players to spend some time with me on this with a machine remote from mine, just to rule out any issues potentially being caused by using the 'same' browser as two people. Can confirm all of the above still occurs, and gleaned a little more info on browser refreshes.

Player moves token, ruler appears for player, disappears for player when they confirm the move, leaves a trail behind on GM map.
GM moves player, ruler appears for GM, disappears for GM when they confirm the move, leaves a trail behind on player map.
Now we have a trail each.
Player refreshes browser, ruler trail on GM map disappears. When the scene reloads, Player can still see the GM-made trail on player's map.
GM refreshes browser, ruler trail on player map disappears. When the scene reloads, GM can still see the player-made trail on GM's map.

I get that that's a fairly long-winded and mildly condescending explanation, but I'd rather be clear and thorough. I'm sadly no developer, and barely a tester, so can't speak on what mechanism is causing this behaviour. Hopefully caewok gets a look back in the thread and can piece it together from all this.

**Comment by jdwpom** [comment] 2024-07-09 08:11
Good (?) news!

It also happens in Firefox 172.0.2. Also tried it in Edge because I hate myself, and it happens there, too. Same thing - if the GM moves a token, its trail remains on the player's screen. This also happens if the token is owned/observed by someone else, though only the last ruler usage remains at any given time. Turning on "Hide GM Token Ruler" at least alleviates the issue for my players, and they don't have to know that my screen is a mess, I guess?
![image](https://github.com/caewok/fvtt-elevation-ruler/assets/892293/5aee2170-23e4-498e-be1a-98cfca547689)

https://github.com/caewok/fvtt-elevation-ruler/assets/892293/11f5f5d3-7095-416a-8268-0eb5ca43bd78

Turning on "Hide GM Token Ruler" at least alleviates the issue for my players, and they don't have to know that my screen is a mess, I guess?

**Comment by Vengrath97** [comment] 2024-07-09 08:15
It happens in Brave and Opera GX too.

**Comment by AnnaMayBelle** [comment] 2024-07-11 21:03
Genius that I am, I _just_ figured out how to change the title. Hopefully it won't slip by unnoticed!

**Comment by caewok** [comment] 2024-07-12 00:18
Fixed in 0.9.9. Thanks everyone for your observations!

**Closed as completed by caewok** 2024-07-12 00:18 UTC
